server:
  port: ${appPort:8800}

# Spring MVC actuator endpoints available via /admin/info, /admin/health, ...
server.servlet-path: /
management.context-path: /admin

# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true


spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
# Bring Postgres docker images using: 
# docker run -d -p 5532:5432 -e DB_NAME=db_dvdrental -e DB_USER=user_dvdrental -e DB_PASSWD=changeit asimio/db_dvdrental:latest
# 172.16.69.133 = Fusion VM Docker host, 5532 Docker host port mapped to container port

multitenancy:
  dvdrental:
    dataSources:
      -
        tenantId: tenant1
        url: jdbc:mysql://localhost:3306/db_dvdrental
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
      -
        tenantId: tenant2
        url: jdbc:mysql://localhost:3306/db_dvdrental1
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
